---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - stovek8s.bud.studio
  resources:
  - snapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stovek8s.bud.studio
  resources:
  - snapshots/finalizers
  verbs:
  - update
- apiGroups:
  - stovek8s.bud.studio
  resources:
  - snapshots/status
  verbs:
  - get
  - patch
  - update
