# This rule is not used by the project stove8s itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the stove8s.bud.studio.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: stove8s
    app.kubernetes.io/managed-by: kustomize
  name: snapshot-editor-role
rules:
- apiGroups:
  - stove8s.bud.studio
  resources:
  - snapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stove8s.bud.studio
  resources:
  - snapshots/status
  verbs:
  - get
